# Generated by Django 3.2.23 on 2023-12-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20231129_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ingreedients',
            new_name='ingredients',
        ),
    ]
